name: Automated testing

on: push

jobs:
  test-linux:
    runs-on: ubuntu-26.04

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v7

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        sudo apt install -y imagemagick
        sudo apt install -y ffmpeg

    - name: Check dependencies
      run: |
        magick -version
        ffmpeg -version

    - name: Install dependencies (build)
      run: npm clean-install
    - name: Clean environment
      run: npm run clean
    - name: Build project for testing
      run: npm run build-test

    - name: Install dependencies (test)
      run: npm clean-install
      working-directory: ./dist
    - name: Run test cases
      run: npm run test
      working-directory: ./dist

  test-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v7

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        winget install --source winget --id 'ImageMagick.Q16'
        winget install --source winget --id 'Gyan.FFmpeg'
        Write-Output "$env:PATH" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Check dependencies
      run: |
        magick -version
        ffmpeg -version

    - name: Install dependencies (build)
      run: npm clean-install
    - name: Clean environment
      run: npm run clean
    - name: Build project for testing
      run: npm run build-test

    - name: Install dependencies (test)
      run: npm clean-install
      working-directory: ./dist
    - name: Run test cases
      run: npm run test
      working-directory: ./dist
